### ISSUE TITLE
Missing documentation for FermentableType

### ISSUE THREAD

**Issue by MichaelWashburnJr** [beerjson/beerjson#76] opened 2018-04-12 15:53 UTC
The link from Fermentable to FermentableType leads to no where. (https://github.com/beerjson/beerjson/blob/master/docs/BeerXML.json.md#fermentable)

**Comment by superroma** [comment] 2018-04-16 14:28
This is caused by #78 - currently a root doc file is empty. Will be fixed after root schema review

**Comment by superroma** [comment] 2018-04-16 14:32
This was a link missing. Actual documentation is here: https://github.com/beerjson/beerjson/blob/master/docs/fermentable.json.md

**Comment by pricelessbrewing** [comment] 2018-06-05 15:52
Closing issue.

**Closed by pricelessbrewing** 2018-06-05 15:52 UTC
